apiVersion: v1
kind: Service
metadata:
  name: dns-server-service
  namespace: default
spec:
  selector:
    app: dns-server
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
    - protocol: TCP
      port: 53
      targetPort: 53
  type: ClusterIP
