apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dns-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
