apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: default
data:
  pki-realm.json: |
    {
      "realm": "PKI-Realm",
      "enabled": true,
      "sslRequired": "all",
      "clients": [
        {
          "clientId": "pki-client",
          "enabled": true,
          "clientAuthenticatorType": "client-x509",
          "redirectUris": [
            "https://example-app.example.com/*"
          ]
        }
      ],
      "identityProviders": [
        {
          "alias": "x509",
          "providerId": "x509",
          "enabled": true,
          "updateProfileFirstLoginMode": "on",
          "trustEmail": true,
          "config": {
            "x509_certificates_header": "X-SSL-CERT",
            "x509_crl_check": "none",
            "x509_identity_source": "SUBJECTDN",
            "x509_identity_source_dn_regex": "CN=(.*?)(?:,|$)"
          }
        }
      ]
    }
