apiVersion: v1
kind: Service
metadata:
  name: dc1-service
  namespace: default
spec:
  selector:
    app: domain-controller
    dc: dc1
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
    - protocol: TCP
      port: 636
      targetPort: 636
    - protocol: TCP
      port: 53
      targetPort: 53
  type: ClusterIP
