apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dc2-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage
