apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc2
  namespace: default
  labels:
    app: domain-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-controller
      dc: dc2
  template:
    metadata:
      labels:
        app: domain-controller
        dc: dc2
    spec:
      containers:
      - name: dc2
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command: ["powershell", "-Command", "Install-ADDSDomainController -DomainName example.com"]
        ports:
        - containerPort: 389 # LDAP port
        - containerPort: 636 # LDAP SSL port
        - containerPort: 53  # DNS
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: dc2-storage
      volumes:
      - name: dc2-storage
        persistentVolumeClaim:
          claimName: dc2-pvc
